In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train = pd.read_csv("housing_train.csv")
test = pd.read_csv("housing_test.csv")

In [3]:
train = train[train["Price"]<np.mean(train["Price"])+3*np.std(train["Price"])]

In [4]:
train.shape

(1216253, 15)

In [5]:
from sklearn.preprocessing import LabelEncoder

categorical=[]
for c in train.columns:
    if train[c].dtype == 'object':
        categorical.append(c)

for c in train.columns:
    if train[c].dtype == 'object':
        lbl = LabelEncoder() 
        lbl.fit(list(train[c].values) + list(test[c].values)) 
        train[c] = lbl.transform(list(train[c].values))
        test[c] = lbl.transform(list(test[c].values))

In [6]:
train.describe()

TID          Date  Property Type       OldvNew      Duration  \
count  1.216253e+06  1.216253e+06   1.216253e+06  1.216253e+06  1.216253e+06   
mean   6.140699e+05  2.278497e+02   2.177213e+00  1.235754e-01  2.372319e-01   
std    3.538115e+05  1.253110e+02   1.553500e+00  3.290967e-01  4.253858e-01   
min    1.000000e+03  0.000000e+00   0.000000e+00  0.000000e+00  0.000000e+00   
25%    3.077530e+05  1.230000e+02   1.000000e+00  0.000000e+00  0.000000e+00   
50%    6.140810e+05  2.280000e+02   3.000000e+00  0.000000e+00  0.000000e+00   
75%    9.205610e+05  3.320000e+02   4.000000e+00  0.000000e+00  0.000000e+00   
max    1.226672e+06  4.540000e+02   4.000000e+00  1.000000e+00  1.000000e+00   

       AddressLine1  AddressLine2        Street      Locality          Town  \
count  1.216253e+06  1.216253e+06  1.216253e+06  1.216253e+06  1.216253e+06   
mean   1.141319e+04  1.187091e+04  9.997531e+04  1.404055e+04  5.473275e+02   
std    2.133970e+04  2.425962e+03  5.652705e+04  5.065763e+03  3.357712e+02   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    1.776000e+03  1.265600e+04  5.114800e+04  1.154400e+04  2.420000e+02   
50%    3.556000e+03  1.265600e+04  1.010040e+05  1.719200e+04  5.020000e+02   
75%    5.273000e+03  1.265600e+04  1.488170e+05  1.719200e+04  8.350000e+02   
max    9.531700e+04  1.265600e+04  1.924860e+05  1.719200e+04  1.145000e+03   

             Taluka      District      Postcode         Price  Price Category  
count  1.216253e+06  1.216253e+06  1.216253e+06  1.216253e+06    1.216253e+06  
mean   1.766544e+02  5.476763e+01  2.980116e+05  3.029596e+02    1.461637e-01  
std    1.029415e+02  3.419676e+01  1.733638e+05  3.246189e+02    3.532704e-01  
min    0.000000e+00  0.000000e+00  0.000000e+00  1.001100e+01    0.000000e+00  
25%    8.000000e+01  3.000000e+01  1.471180e+05  1.450000e+02    0.000000e+00  
50%    1.800000e+02  4.900000e+01  2.969360e+05  2.300000e+02    0.000000e+00  
75%    2.660000e+02  9.000000e+01  4.481320e+05  3.540000e+02    0.000000e+00  
max    3.520000e+02  1.120000e+02  5.967070e+05  5.830873e+03    1.000000e+00

In [7]:
print('Shape train: {}\nShape test: {}'.format(train.shape, test.shape))

Shape train: (1216253, 15)
Shape test: (2066, 14)


In [8]:
train = train.drop(["TID"], axis=1)
test = test.drop(["TID"], axis=1)

In [9]:
y = train["Price"]

In [10]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

model = RandomForestRegressor(n_estimators=50, n_jobs=-1)
print(cross_val_score(model, train.drop(["Price"], axis=1), y))

/Users/vrishank/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


[0.32653577 0.48931917 0.33267992]


In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

model = RandomForestRegressor(n_estimators=50, n_jobs=-1)
print(cross_val_score(model, train.drop(["Price"], axis=1)[:50000], y[:50000]))

In [57]:
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score

model = GradientBoostingRegressor()
print(cross_val_score(model, train.drop(["Price"], axis=1)[:50000], y[:50000]))

/Users/vrishank/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


[0.29072078 0.30649728 0.32731902]


In [61]:
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_score

model = XGBRegressor()
print(cross_val_score(model, train.drop(["Price"], axis=1)[:100000], y[:100000]))

/Users/vrishank/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


[0.32342498 0.33014921 0.34016163]
